import { createClient } from '@supabase/supabase-js'
import { createBrowserClient, createServerClient } from '@supabase/ssr'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

// Client-side Supabase client
export const createClientComponentClient = () => {
  return createBrowserClient(supabaseUrl, supabaseAnonKey)
}

// Database types (will be generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      tasks: {
        Row: {
          id: string
          content: string
          category: string
          priority: string
          status: string
          deadline: string | null
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          id?: string
          content: string
          category: string
          priority: string
          status?: string
          deadline?: string | null
          created_at?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          id?: string
          content?: string
          category?: string
          priority?: string
          status?: string
          deadline?: string | null
          created_at?: string
          updated_at?: string
          user_id?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          provider: string
          provider_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          avatar_url?: string | null
          provider?: string
          provider_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          provider?: string
          provider_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
      }
    }
  }
}